# Xóa dòng cũ bị lỗi đi và thay bằng dòng này:
spring.datasource.url=jdbc:mariadb://localhost:3306/UserDB
spring.datasource.username=root
spring.datasource.password=root

# Thêm dòng này để Hibernate biết chính xác là MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true