spring.datasource.url=jdbc:mariadb://localhost:3306/FoodDeliveryDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
# Hibernate tự động nhận diện MariaDB nên không cần khai báo dialect thủ công