# Cho phép truy c?p giao di?n qu?n lý database qua trình duy?t
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# C?u hình k?t n?i
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hi?n th? SQL ra console ?? debug
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update